/**
 * Seed Function
 * (sails.config.bootstrap)
 *
 * A function that runs just before your Sails app gets lifted.
 * > Need more flexibility?  You can also create a hook.
 *
 * For more information on seeding your app with fake data, check out:
 * https://sailsjs.com/config/bootstrap
 */

module.exports.bootstrap = async function() {

  sails.argon2 = require('argon2');
  if (await User.count() > 0) {
    console.log('No Vacia');
    return;
  }

  console.log('Vacia');
  await User.createEach([
    { username: 'Santiago',
      email: 'santiagovietto5@hotmail.com',
      password: await sails.argon2.hash('manzana123') },

    { username: 'Silvia',
      email: 'lucas10Herrera@hotmail.com',
      password: await sails.argon2.hash('manzana111') },
  ]);


  await Habitacion.createEach([
    { numero: '101',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '102',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '103',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '104',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '105',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '106',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '107',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '108',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '109',
      precio: '8000',
      tipoHabitacion: 'Cuadruple',
      estado: 'Disponible' },
    { numero: '201',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '202',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '203',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '204',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '205',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '206',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '207',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '208',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '209',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '210',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '211',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '212',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '213',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '214',
      precio: '8000',
      tipoHabitacion: 'Cuadruple',
      estado: 'Disponible' },
    { numero: '215',
      precio: '8000',
      tipoHabitacion: 'Cuadruple',
      estado: 'Disponible' },
    { numero: '216',
      precio: '8000',
      tipoHabitacion: 'Cuadruple',
      estado: 'Disponible' },
    { numero: '217',
      precio: '8000',
      tipoHabitacion: 'Cuadruple',
      estado: 'Disponible' },
    { numero: '218',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '301',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '302',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '303',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '204',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '205',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '206',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '207',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '208',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '209',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '210',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '211',
      precio: '5500',
      tipoHabitacion: 'Doble',
      estado: 'Disponible' },
    { numero: '212',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '213',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '214',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '215',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '216',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '217',
      precio: '7000',
      tipoHabitacion: 'Triple',
      estado: 'Disponible' },
    { numero: '218',
      precio: '8000',
      tipoHabitacion: 'Cuadruple',
      estado: 'Disponible' },
  ]);

};
